import { Background } from '@/components/background';
import { Header } from '@/components/header';
import { ThemeProvider } from '@/components/theme-provider';
import { ThemeToggle } from '@/components/theme-toggle-button';
import type { Metadata } from 'next';
import './globals.css';
import { inter, jetbrainsMono, sourceSerif4 } from '@/lib/fonts';

export const metadata: Metadata = {
    title: 'Toby Nguyen - Porfolio',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${inter.variable} ${sourceSerif4.variable} ${jetbrainsMono.variable} antialiased`}>
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                    <Header />
                    <Background>{children}</Background>
                    <ThemeToggle />
                </ThemeProvider>
            </body>
        </html>
    );
}
